config/routes.rb
Rails.application.routes.draw do
  resources :properties do
    resources :repairs do
      collection do
        get :new_appointment
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block
  include ActiveModel::Model

  attr_accessor :propertyReference, :postcode, :address, :managerName,
                :managerPhone, :managerEmail, :floors, :entranceDoors, :lifts,
                :heating

  def self.find_by_dwelling(dwelling_reference)
    new_from_json(HackneyApi.new.get_block_for_dwelling(dwelling_reference))
  end

  def self.new_from_json(json)
    new(json)
  end
end

app/models/dwelling.rb
class Dwelling
  include ActiveModel::Model

  attr_accessor :propertyReference, :postcode, :address, :maintainable,
                :floor, :residents, :heating, :toilets, :bathrooms

  def self.find(dwelling_reference)
    new_from_json(HackneyApi.new.get_property(dwelling_reference))
  end

  def self.new_from_json(json)
    new(json)
  end
end

app/models/estate.rb
class Estate
  include ActiveModel::Model

  attr_accessor :propertyReference, :postcode, :address, :managerName,
                :managerPhone, :managerEmail

  def self.find_by_dwelling(dwelling_reference)
    new_from_json(HackneyApi.new.get_estate_for_dwelling(dwelling_reference))
  end

  def self.new_from_json(json)
    new(json)
  end
end

app/models/repair.rb
class Repair
  include ActiveModel::Model

  attr_accessor :repairRequestReference, :propertyReference, :problemDescription,
                :priority, :contactName, :contactPhone, :workOrders

  def self.find_all_by_property_reference(dwelling_reference)
    HackneyApi.new.find_repairs_by_property_reference(property_reference: dwelling_reference).collect do |x|
      new_from_json(x)
    end
  end

  def self.find(repairRequestReference)
    response = HackneyApi.new.get_repair(repair_request_reference: repairRequestReference)
    new_from_json(response)
  end

  def self.new_from_json(json)
    json['contactName'] = json['contact']['name']
    json['contactPhone'] = json['contact']['phone']
    json.delete('contact')
    json['workOrders'] = json['workOrders'].map do |work_order_json|
      WorkOrder.new_from_json(work_order_json)
    end
    new(json)
  end

  def priority_text
    case self.priority
    when 'E'
      'Emergency'
    when 'G'
      'Gas Servicing'
    when 'I'
      'Immediate'
    when 'N'
      'Normal'
    when 'O'
      'Out of hours'
    when 'P'
      'Planned Maintenance'
    when 'U'
      'Urgent'
    else
      self.priority
    end
  end

  def trades
    workOrders.collect {|wo| wo.tasks.collect {|t| t.trade}}.flatten.uniq
  end
end

app/models/resident.rb
class Resident
  include ActiveModel::Model

  attr_accessor :residentReference, :name, :last_call

  def self.find_all_by_property_reference(dwelling_reference)
    HackneyApi.new.find_residents_by_property_reference(dwelling_reference).collect do |x|
      new_from_json(x)
    end
  end

  def self.new_from_json(json)
    new(json)
  end
end

app/models/task.rb
class Task
  include ActiveModel::Model

  attr_accessor :sorCode, :dueDate, :supplierReference, :estimatedCost, :trade,
                :completedDate, :description

  def self.new_from_json(json)
    json['completedDate'] = DateTime.parse(json['completedDate']) if json['completedDate'].present?
    json['dueDate'] = DateTime.parse(json['dueDate']) if json['dueDate'].present?
    new(json)
  end

  def progress_class_name

  end

  def completed?
    self.completedDate.present?
  end

  def cancelled?
    false
  end
end

app/models/work_order.rb
class WorkOrder
  include ActiveModel::Model

  attr_accessor :supplierReference, :workOrderReference, :estimatedCost,
                :repairType, :status, :dueDate, :expectedCompletion, :attendedDate,
                :attendedBy, :outcome, :cancelledDate, :sorCode, :tasks

  def self.new_from_json(json)
    json['tasks'] = json['tasks'].map do |task_json|
      Task.new_from_json(task_json)
    end
    json['dueDate'] = DateTime.parse(json['dueDate']) if json['dueDate'].present?
    json['expectedCompletion'] = DateTime.parse(json['expectedCompletion']) if json['expectedCompletion'].present?
    json['attendedDate'] = DateTime.parse(json['attendedDate']) if json['attendedDate'].present?
    json['cancelledDate'] = DateTime.parse(json['cancelledDate']) if json['cancelledDate'].present?
    new(json)
  end

  def completed?
    self.status == 'Completed'
  end

  def in_progress?
    self.status == 'In Progress'
  end

  def cancelled?
    self.status == 'Cancel Order'
  end

  def progress_class_name
    case self.status
    when 'Completed'
      'completed'
    when 'In Progress'
      'progress'
    when 'Cancel Order'
      'cancelled'
    else
      'unknown'
    end
  end

  def trades
    tasks.collect {|t| t.trade}.uniq
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    if params[:post_code]
      @properties = AddressFinder.new.find(params[:post_code])
      if @properties.present?
        @block = Block.find_by_dwelling(property_reference: @properties.first.property_reference)
        @estate = Estate.find_by_dwelling(property_reference: @properties.first.property_reference)
      end
    end
  end

  def show
    @property = Dwelling.find(property_reference: params[:id])
    @block = Block.find_by_dwelling(property_reference: params[:id])
    @estate = Estate.find_by_dwelling(property_reference: params[:id])
    @residents = Resident.find_all_by_property_reference(property_reference: params[:id])
  end
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  before_action :find_property
  def index
    @repairs = Repair.find_all_by_property_reference(@property.propertyReference)
  end

  def show
    @repair = Repair.find(params[:id])
  end

  private
  def find_property
    @property = Dwelling.find(property_reference: params[:property_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "RCC"

    = stylesheet_link_tag "application"
    -# = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application"
    = csrf_meta_tag

  %body

    .grid-y.rcc-app
      .cell
        %nav.top-bar
          .top-bar-left
            %ul.menu
              %li.menu-text.app-title
                Hackney Repairs Contact Centre
          .top-bar-right
            %ul.menu
              %li.menu-text.light.user-name
                Lisa Roomian
              %li
                =link_to "Log out", ' '

      .cell
        .grid-x.grid-padding-x
          .medium-2.cell.side-nav
            %ul.vertical.menu
              %li.menu-item.is-active
                =link_to "Find address", '/properties'
              %li.menu-item
                =link_to "Find repair", '/properties'

          .medium-10.cell.main

            = yield

app/views/properties/_dwelling_info.html.haml
%h4
  Overview for dwelling
%p
  = @property.address

.grid-x
  .cell.medium-6
    %p
      %span.list-item
        = @property.residents
        residents

      - if @property.floor
        %span.list-item
          = "#{@property.floor}#{@property.floor.ordinal} floor"

      %span.list-item
        = pluralize @property.toilets, 'toilet'

  .cell.medium-6
    %p
      %span.list-item
        Heating:
        = @property.heating

      %span.list-item
        = pluralize @property.bathrooms, 'bathroom'

app/views/properties/_estate_info.html.haml
%h4
  Overview for
  = @block.postcode

%p.title
  %strong
    Block
%p
  = @block.address

%p.title
  %strong
    Patch Manager
%p
  %span.list-item
    = @block.managerName
  %span.list-item
    = mail_to @block.managerEmail
  %span.list-item
    = link_to @block.managerPhone, "tel:#{@block.managerPhone}"

%p.title
  %strong
    Block overview

.grid-x
  .cell.medium-6
    %p
      %span.list-item
        = pluralize @block.floors, 'floor'

      %span.list-item
        = pluralize @block.entranceDoors, 'entrance door'

      %span.list-item
        = pluralize @block.lifts, 'lift'

  .cell.medium-6
    %p
      %span.list-item
      Heating:
      = @block.heating

%p.title
  %strong
    Estate
%p
  %span.list-item
    = @estate.address

%p.title
  %strong
    Estate Manager
%p
  %span.list-item
    = @estate.managerName
  %span.list-item
    = mail_to @estate.managerEmail
  %span.list-item
    = link_to @estate.managerPhone, "tel:#{@estate.managerPhone}"

app/views/properties/index.html.haml
.grid-x.grid-padding-x
  .medium-7.cell.content
    = form_tag properties_path, method: :get do
      = label_tag 'post_code', 'Find a property by postcode', class: 'h4'
      .input-group
        = text_field_tag :post_code, '', class: 'input-group-field', placeholder: 'Enter postcode...'
        .input-group-button
          = button_tag 'Find', class: 'button', type: :submit

    - if defined?(@properties)
      - if @properties.present?
        %h4
          List of properties for
          = params[:post_code]

        %ul.list-group
          - @properties.each do |property|
            %li.list-group-item
              = link_to property.address, property_path(property.property_reference)
      - else
        %p No properties found

  .medium-5.cell.side-info
    - if defined?(@properties) && @properties.present?
      = render partial: 'estate_info'

app/views/properties/show.html.haml
.grid-x.grid-padding-x
  .medium-7.cell.content
    %h2
      = @property.address
      = @property.postcode

    %ul.list-group
      - @residents.each do |resident|
        %li.list-group-item
          = link_to resident.name, property_repairs_path(@property.propertyReference, resident: resident.residentReference)


      - if @residents.blank?
        No residents found

    = link_to "The resident is not on the list", property_repairs_path(@property.propertyReference)

  .medium-5.cell.side-info
    = render partial: 'dwelling_info'
    = render partial: 'estate_info'

app/views/repairs/index.html.haml
%header
  .grid-x.grid-margin-x.header-summary
    .cell.medium-4
      %p
        %strong
          Property address
        %span.list-item
          = @property.address

        %span.list-item
          = @property.postcode

    .cell.medium-8
      %strong
        Resident information
      .grid-x
        .cell.medium-6
          %span.list-item
            Bob Smith
          %span.list-item
            07556788932
        .cell.medium-6
          %span.label.warning
            Cautionary contact
          %span
            CLA

%nav.grid-x.grid-margin-x#sub-nav
  %ul.cell.menu.expanded
    %li
      = link_to "Raise a repair", new_property_repair_path(property: @property)
    %li.is-active
      = link_to "Dwelling repairs", " "
    %li
      = link_to "Block repairs", " "
    %li
      = link_to "Estate repairs", " "
    %li
      = link_to "Tenant's Information", " "

.grid-x.grid-margin-x.repairs-list-view.property-summary
  .cell.medium-8
    %p
      %strong
        Dwelling overview
    .property-summary
      - if @property.floor
        %span
          = "#{@property.floor}#{@property.floor.ordinal} floor"

      %span
        = pluralize @property.residents, 'resident'
      %span
        = @property.heating
      %span
        = pluralize @property.toilets, 'toilet'
      %span
        = pluralize @property.bathrooms, 'bathroom'

  .cell.medium-4
    %br
    = link_to "Raise a repair for this dwelling", new_property_repair_path(property: @property), :class=>"button"

.grid-x.grid-margin-x.mini-nav
  .nav
    .ul.breadcrumbs
      %li
        Dwelling repairs history

.grid-x.grid-margin-x.repairs-list-view.repairs-history
  .cell.medium-8

    - @repairs.each do |repair|
      .repair.card.status-progress
        .card-section
          .grid-x
            .cell
              -# repair_req_number
              %span.leading-number
                = link_to repair.repairRequestReference, property_repair_path(@property.propertyReference, repair.repairRequestReference)
              -# Repair priority
              %span.priority
                = repair.priority
              %span.date
                Created 3 days ago, 20 Jun
              -# Show each trade from tasks from all WO
              %span.trade.float-right
                PLM
              %hr.tight
          .grid-x.grid-margin-x
            .cell
              %p.repair-description
                = repair.problemDescription
            .cell.medium-8
              -# Repair request status based on completion of tasks in the work order
              %span.status-text.list-item
                Tasks awaiting completion
              -# Summary of status for tasks
              %span.status-breakdown.list-item
                1 task in progress, 2 tasks completed
            .cell.medium-4
              = link_to "View details", property_repair_path(@property.propertyReference, repair.repairRequestReference)

app/views/repairs/new.html.haml
%header
  .grid-x.grid-margin-x.header-summary
    .cell.medium-4
      %p
        %strong
          Property address
        %span.list-item
          = @property.address

        %span.list-item
          = @property.postcode

    .cell.medium-8
      %strong
        Resident information
      .grid-x
        .cell.medium-6
          %span.list-item
            John Tenant
          %span.list-item
            07556788932
        .cell.medium-6
          %span.list-item
            Cautionary contact

%nav.grid-x.grid-margin-x#sub-nav
  %ul.cell.menu.expanded
    %li.is-active
      = link_to "Raise a repair", " "
    %li
      = link_to "Dwelling repairs", " "
    %li
      = link_to "Block repairs", " "
    %li
      = link_to "Estate repairs", " "
    %li
      = link_to "Tenant's Information", " "


.grid-x.grid-margin-x.mini-nav
  .nav
    .ul.breadcrumbs
      %li
        Raise a repair
      %li
        Add repair details
      %li.disabled
        Add repair appointment

.grid-x.grid-margin-x.add-repair-section
  .cell.medium-6.create-repair-form
    %br
    = form_tag new_appointment_property_repairs_path(property: @property), method: :get do
      %p.h6
        Is this the correct resident's contact number?
      %p.help-text
        If yes please continue
      %strong.h5
        07556788932
      %span
        = link_to "Change", " "
      %br
      %br
      %label
        Describe repair problem
        = text_area_tag :problem_description, ' ', :rows => 5

      %label
        SOR code
        = text_field_tag :sor_code, ''
      %p.help-text
        Please use a Keyfax to find the right SOR code for this repair

      %label
        Repair priority
        = text_field_tag :repair_priority, ''

      = button_tag 'Save and next', class: 'button', type: :submit

app/views/repairs/new_appointment.html.haml
%header
  .grid-x.grid-margin-x.header-summary
    .cell.medium-4
      %p
        %strong
          Property address
        %span.list-item
          = @property.address

        %span.list-item
          = @property.postcode

    .cell.medium-8
      %strong
        Resident information
      .grid-x
        .cell.medium-6
          %span.list-item
            John Tenant
          %span.list-item
            07556788932
        .cell.medium-6
          %span.list-item
            Cautionary contact

%nav.grid-x.grid-margin-x#sub-nav
  %ul.cell.menu.expanded
    %li.is-active
      = link_to "Raise a repair", " "
    %li
      = link_to "Dwelling repairs", " "
    %li
      = link_to "Block repairs", " "
    %li
      = link_to "Estate repairs", " "
    %li
      = link_to "Tenant's Information", " "


.grid-x.grid-margin-x.mini-nav
  .nav
    .ul.breadcrumbs
      %li.disabled
        Raise a repair
      %li.disabled
        Add repair details
      %li
        Add repair appointment

.grid-x.grid-margin-x.add-repair-section
  .cell.medium-6.create-repair-form
    %br
    %strong
      Available appointments
    = form_tag method: :get do
      %fieldset.fieldset
        %legend
          Choose one of the appointment slots
        %span.list-item
          = radio_button_tag(:appointment, "1")
          = label_tag 'appointment_1', 'Monday, 22nd July, 8am-12am'
        %span.list-item
          = radio_button_tag(:appointment, "2")
          = label_tag 'appointment_2', 'Monday, 22nd July, 12pm-4:15pm'
        %span.list-item
          = radio_button_tag(:appointment, "3")
          = label_tag 'appointment_3', 'Monday, 22nd July, 8am-4:15pm'

      %strong
        If none of these slots work please book an appointment directly in DRS

      %fieldset.fieldset
        %span.list-item
          = check_box_tag(:drs)
          = label_tag 'drs', 'Yes, appointment booked in DRS'



      = button_tag 'Finish raising repair', class: 'button', type: :submit

  .cell.medium-6
    .callout.success
      %h5.text-success
        Repair created
      %p
        Request number: 888484923
      %p
        Work Order nuber: 9999999

app/views/repairs/show.html.haml
%header
  .grid-x.grid-margin-x.header-summary
    .cell.medium-4
      %p
        %strong
          Property address
        %span.list-item
          = @property.address

        %span.list-item
          = @property.postcode

    .cell.medium-8
      %strong
        Resident information
      .grid-x
        .cell.medium-6
          %span.list-item
            = @repair.contactName
          %span.list-item
            = @repair.contactPhone
        .cell.medium-6
          %span.list-item.label.warning
            Cautionary contact

%nav.grid-x.grid-margin-x#sub-nav
  %ul.cell.menu.expanded
    %li
      = link_to "Raise a repair", " "
    %li.is-active
      = link_to "Dwelling repairs", " "
    %li
      = link_to "Block repairs", " "
    %li
      = link_to "Estate repairs", " "
    %li
      = link_to "Tenant's Information", " "

.grid-x.grid-margin-x.repairs-list-view.property-summary
  .cell.medium-8
    %p
      %strong
        Dwelling overview
    .property-summary
      - if @property.floor
        %span
          = "#{@property.floor}#{@property.floor.ordinal} floor"

      %span
        = pluralize @property.residents, 'resident'
      %span
        = @property.heating
      %span
        = pluralize @property.toilets, 'toilet'
      %span
        = pluralize @property.bathrooms, 'bathroom'

  .cell.medium-4
    %br
    = link_to "Raise a repair for this dwelling", new_property_repair_path(property: @property), :class=>"button"

.grid-x.grid-padding-x.mini-nav
  .nav
    .ul.breadcrumbs
      %li
        = link_to "Dwelling repairs history"
      %li
        = "Repair details (#{@repair.repairRequestReference})"

.grid-x.grid-padding-x.repair-details-page
  .cell
    -# Repair request card
    %h6
      Repair request
    -# The card top border color will change based on class // { class: status-progress, status-complete, status-cancelled }
    .repair.card.status-progress
      .card-section
        .grid-x
          .cell
            %span.leading-number
              = @repair.repairRequestReference
            %span.priority
              = @repair.priority_text
            %span.date
              Created 3 days ago, 20 Jun
            - @repair.trades.each do |trade|
              %span.trade.float-right
                = trade
            %hr.tight
        .grid-x.grid-margin-x
          .cell.medium-8
            %p.repair-description
              = @repair.problemDescription
            .cell
              -# Repair request status based on completion of tasks in the work order
              %span.status-text.list-item
                Tasks awaiting completion
              -# Summary of status for tasks
              %span.status-breakdown.list-item
                1 task in progress, 2 tasks completed
          .cell.medium-4
            %span.tenant-info.list-item
              Reported by Sandra Tenant
            %span.list-item
              tel: 07446788345
            %br
            %span.agent-info.list-item
              Raised by Tom Jerry
            %span.list-item
              tom.jerry@hackney.gov.uk
        .grid-x.grid-margin-x


    - @repair.workOrders.each.with_index do |work_order, index|
      %h6
        Repair work order
        = index + 1
        of
        = @repair.workOrders.count
      -# The card top border color will change based on class // { class: status-progress, status-complete, status-cancelled }
      .repair.card.status-progress
        .card-section
          .grid-x
            .cell
              %span.leading-number
                = work_order.workOrderReference
              - work_order.trades.each do |trade|
                %span.trade.float-right
                  = trade
              %span{class: "status-text-#{work_order.progress_class_name}"}
                = work_order.status
              %span
                - if work_order.in_progress?
                  expected completion on
                - else
                  on
              %span.date
                - if work_order.in_progress?
                  = work_order.expectedCompletion.to_s(:short)
                - elsif work_order.completed?
                  = work_order.attendedDate.to_s(:short)
                - elsif work_order.cancelled?
                  = work_order.cancelledDate.to_s(:short)
              %hr.tight
          .grid-x.grid-margin-x
            .cell.medium-8
              - if work_order.completed?
                %span.list-item
                  Attended by:
                  = work_order.attendedBy
                  on
                  = work_order.attendedDate.to_s(:short)
                %span.description
                  = work_order.outcome
            .cell.medium-4
              %span.supplier.list-item
                = work_order.supplierReference
              %span.list-item
                tel: 07446788345
              %span.list-item
                Estimated cost:
                = number_to_currency work_order.estimatedCost
          -# Show notes and tasks
          .grid-x.grid-padding-x.card-split-heading
            .cell.medium-6.card-half
              .h6
                Notes
            .cell.medium-6.card-half
              .h6
                Tasks
          .grid-x.grid-padding-x.card-split-content
            -# NOTES
            .cell.medium-6.card-half
              -# For each note in notes show DESC
              .note
                %span.list-item.note-helptext
                  21 June 2018 by Sammy Wonder
                %p
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

              .note
                %span.list-item.note-helptext
                  25 May 2018 by Gerard of Rivia
                %p
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

            .cell.medium-6.card-half.no-pad
              - work_order.tasks.each do |task|
                .task.task-completed
                  .grid-x
                    .cell
                      SOR:
                      %span.leading-number
                        = task.sorCode
                      %span{class: "status-text-#{task.progress_class_name}"}
                        - if task.completed?
                          Completed on
                          = task.completedDate.to_s(:short)
                        - elsif task.cancelled?
                        - else
                          Due
                          = task.dueDate.to_s(:short)
                      %span.trade-sm.float-right
                        = task.trade

                    .cell
                      %span
                        = task.supplierReference
                      %span
                        Estimated Cost:
                        = number_to_currency task.estimatedCost
                    .cell
                      %p
                        = task.description